import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";

import "./globals.css";

import { Theme, ThemePanel } from "@radix-ui/themes";

import NavBar from "./NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >
        
        <Theme appearance="dark" accentColor="yellow" panelBackground="solid" scaling="110%">

        <NavBar />
        <main className="p-5">{children}</main>
        <ThemePanel />
        </Theme>

      </body>
    </html>
  );
}
